# Generated by Django 6.0.6 on 2026-06-08 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='instructions',
            field=models.TextField(default='Добавьте инструкцию приготовления', verbose_name='Инструкция приготовления'),
            preserve_default=False,
        ),
    ]
