# Generated by Django 6.0.6 on 2026-06-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_recipe_instructions'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='category',
            field=models.CharField(choices=[('salad', '🥗 Салат'), ('soup', '🍲 Суп'), ('main', '🍝 Горячее'), ('dessert', '🍰 Десерт')], default='main', max_length=10, verbose_name='Категория'),
        ),
    ]
